# 实际开发的时候，database配置务必修改一下

development:
  adapter: mysql
  encoding: utf8
  database: pin-stories
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: pin-stories-test
  username: root
  password: root
  host: localhost
  
production:
  adapter: mysql
  encoding: utf8
  database: pin-stories-production
  username: root
  password: root
  host: localhost
